### PR TITLE
Update MsgPackDecoder.kt

### PR DESCRIPTION
**Pull request by umerov1999**
fix class decoder

### CODE REVIEW

**Comment by esensar** [comment]
Hi!
Thank you for you PR.

Can you add some description for this?
Is there a bug that this PR fixes? If so, can you add some description regarding that bug and if possible a test for it.

**Comment by umerov1999** [comment]
> Hi! Thank you for you PR.
> 
> Can you add some description for this? Is there a bug that this PR fixes? If so, can you add some description regarding that bug and if possible a test for it.

sample.json.txt - this file is messagepack converted to json
Test.kt - test decoding
[dlg.lastMessage not decoded!]

[test.tar.gz](https://github.com/esensar/kotlinx-serialization-msgpack/files/10539038/test.tar.gz)

**Comment by esensar** [comment]
Hi, sorry for the long delay.

I just checked out your test and it seems to be working fine after one small update in one of your models.

In `VKApiMessage` `out` is defined as a boolean, but it is an integer in the JSON you sent. Parsing fails there, so changing it to a numeric type makes this work.

**Comment by esensar** [comment]
My bad, when changing to `ignoreUnknownKeys` it is `null` as you reported.

**Comment by esensar** [comment]
Fix will be released in `0.5.4`

**Pull request closed without merging**
